services:
  backend: 
    image: 'kies-backend:latest'
    build: 
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080" # temporaire, à supprimer en prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kiesdb
      - SPRING_DATASOURCE_USERNAME=kies
      - SPRING_DATASOURCE_PASSWORD=kies
  
  frontend:
    image: 'kies-frontend:latest'
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - PUBLIC_API_URL=http://backend:8080
  
  db:
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_DB=kiesdb
      - POSTGRES_USER=kies
      - POSTGRES_PASSWORD=kies
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kies -d kiesdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: 'dpage/pgadmin4:9.2.0'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@kies.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: