spring.application.name=kies

# Database config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kiesdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:kies}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kies}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true